jenkins:
  build: "jenkins/"
  ports:
    - "8080:8080"
  environment:
    - JAVA_OPTS:-Djava.awt.headless=true
  volumes:
    - /var/jenkins_home

sonarqube:
  image: sonarqube
  ports:
   - "9000:9000"
  links:
   - db
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
  volumes_from:
   - plugins

db:
  image: postgres
  volumes_from:
    - datadb
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar

datadb:
  image: postgres
  volumes:
    - /var/lib/postgresql
  command: /bin/true

plugins:
  image: sonarqube
  volumes:
   - /opt/sonarqube/extensions
   - /opt/sonarqube/lib/bundled-plugins
  command: /bin/true